import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

// import Head from "next/head";

import { config } from "@fortawesome/fontawesome-svg-core";
import React from "react";
// import LinksToPages from "../components/LinksToPages";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

config.autoAddCss = false;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        {/* <LinksToPages /> */}
        {children}
      </body>
    </html>
  );
}
